name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Build and push Docker image
        run: |
          docker build -t multimind-ai-platform:${{ github.sha }} .
          docker tag multimind-ai-platform:${{ github.sha }} thirisha2006-S/multimind-ai-platform:latest
        shell: bash
